-- 확인
SELECT ID, PASS, NAME, LEV, ENTER, GENDER, PHONE FROM EMPLOYEES;

-- 추가
INSERT INTO EMPLOYEES(ID, PASS, NAME, LEV, ENTER, GENDER, PHONE) VALUES ('somi', '1234', '이소미', 'B', SYSDATE, '2', '010-1234-1234');

-- login
SELECT ID, PASS, NAME, LEV, GENDER, PHONE FROM EMPLOYEES WHERE ID = 'admin' AND PASS = '1111';

-- 수정
UPDATE EMPLOYEES SET PASS = '1111', NAME = '이소미', LEV = 'A', ENTER = SYSDATE, GENDER = 2, PHONE = '010-5555-5555' WHERE ID = 'somi';

-- 삭제
DELETE FROM EMPLOYEES WHERE ID = 'somi';

SELECT *
 FROM EMPLOYEES;

-- usercheck
SELECT PWD FROM MEMBER WHERE USERID = 'somi';
